--197. 上升的温度
--
--给定一个 Weather 表，编写一个 SQL 查询，来查找与之前（昨天的）日期相比温度更高的所有日期的 Id。
--
--+---------+------------------+------------------+
--| Id(INT) | RecordDate(DATE) | Temperature(INT) |
--+---------+------------------+------------------+
--|       1 |       2015-01-01 |               10 |
--|       2 |       2015-01-02 |               25 |
--|       3 |       2015-01-03 |               20 |
--|       4 |       2015-01-04 |               30 |
--+---------+------------------+------------------+
--例如，根据上述给定的 Weather 表格，返回如下 Id:
--
--+----+
--| Id |
--+----+
--|  2 |
--|  4 |
--+----+
-- 采用TIMESTAMPDIFF，不使用连表
select next.`Id` from `Weather` pre, `Weather` next where TIMESTAMPDIFF(day, pre.`RecordDate`, next.`RecordDate`) = 1 and pre.`Temperature` < next.`Temperature`;
-- 采用DATEDIFF，内联表
select w.Id from `Weather` w INNER join `Weather` n on DATEDIFF(w.RecordDate, n.RecordDate) = 1 where w.`Temperature` > n.`Temperature`;